/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.7_embla-carousel@8.6.0_typescript@5.9.3_vite@6.4.3_ji_938d26f93602d08cf160aaf0f3f6cc13/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  }
}
