import { apiJson, jsonBody, qs, type Dict } from './client'

export const inventory = () => apiJson('/api/admin/spine/inventory')
export const tenants = () => apiJson('/api/admin/spine/tenants')
export const config = () => apiJson('/api/admin/spine/config')
export const audit = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/audit${qs(p)}`)
export const dataQuality = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/data-quality${qs(p)}`)
export const dataQualityProducts = (site: string, p: Dict<any> = {}) => apiJson(`/api/admin/spine/data-quality/${encodeURIComponent(site)}/products${qs(p)}`)
export const aosenFieldQualityAcceptance = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/acceptance/aosen/field-quality${qs(p)}`)
export const aosenAcceptanceActionPlan = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/acceptance/aosen/action-plan${qs(p)}`)
export const siteCrawlerConfig = (site: string) => apiJson(`/api/admin/spine/sites/${encodeURIComponent(site)}/crawler-config`)
export const siteCrawlerConfigUpdate = (site: string, payload: Dict<any>) => apiJson(`/api/admin/spine/sites/${encodeURIComponent(site)}/crawler-config`, { method: 'PATCH', ...jsonBody(payload) })
export const siteCrawlerConfigTestPriceSource = (site: string, payload: Dict<any>) => apiJson(`/api/admin/spine/sites/${encodeURIComponent(site)}/crawler-config/test-price-source`, { method: 'POST', ...jsonBody(payload) })
export const crawlEnqueue = (payload: Dict<any>) => apiJson('/api/admin/spine/crawl/enqueue', { method: 'POST', ...jsonBody(payload) })
export const promotionsRebuild = (payload: Dict<any>) => apiJson('/api/admin/spine/promotions/rebuild', { method: 'POST', ...jsonBody(payload) })
export const promotionSignalsImport = (payload: Dict<any>) => apiJson('/api/admin/spine/promotion-signals/import', { method: 'POST', ...jsonBody(payload) })
export const promotionSignalsTemplate = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/promotion-signals/template${qs(p)}`)
export const promotionSignalsValidate = (payload: Dict<any>) => apiJson('/api/admin/spine/promotion-signals/validate', { method: 'POST', ...jsonBody(payload) })
export const productFieldFixesImport = (payload: Dict<any>) => apiJson('/api/admin/spine/product-field-fixes/import', { method: 'POST', ...jsonBody(payload) })
export const productFieldFixesTemplate = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/product-field-fixes/template${qs(p)}`)
export const productFieldFixesValidate = (payload: Dict<any>) => apiJson('/api/admin/spine/product-field-fixes/validate', { method: 'POST', ...jsonBody(payload) })
export const skuTargetsImport = (payload: Dict<any>) => apiJson('/api/admin/spine/sku-targets/import', { method: 'POST', ...jsonBody(payload) })
export const skuTargetsTemplate = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/sku-targets/template${qs(p)}`)
export const skuTargetsValidate = (payload: Dict<any>) => apiJson('/api/admin/spine/sku-targets/validate', { method: 'POST', ...jsonBody(payload) })
export const analyticsRecompute = (payload: Dict<any>) => apiJson('/api/admin/spine/analytics/recompute', { method: 'POST', ...jsonBody(payload) })
export const salesSignalsImport = (payload: Dict<any>) => apiJson('/api/admin/spine/sales-signals/import', { method: 'POST', ...jsonBody(payload) })
export const salesSignalsTemplate = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/sales-signals/template${qs(p)}`)
export const salesSignalsValidate = (payload: Dict<any>) => apiJson('/api/admin/spine/sales-signals/validate', { method: 'POST', ...jsonBody(payload) })
export const reviewHistoryImport = (payload: Dict<any>) => apiJson('/api/admin/spine/review-history/import', { method: 'POST', ...jsonBody(payload) })
export const reviewHistoryTemplate = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/review-history/template${qs(p)}`)
export const reviewHistoryValidate = (payload: Dict<any>) => apiJson('/api/admin/spine/review-history/validate', { method: 'POST', ...jsonBody(payload) })
export const thirdPartyMetricsImport = (payload: Dict<any>) => apiJson('/api/admin/spine/third-party-metrics/import', { method: 'POST', ...jsonBody(payload) })
export const thirdPartyMetricsTemplate = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/third-party-metrics/template${qs(p)}`)
export const thirdPartyMetricsValidate = (payload: Dict<any>) => apiJson('/api/admin/spine/third-party-metrics/validate', { method: 'POST', ...jsonBody(payload) })
export const proxies = () => apiJson('/api/admin/spine/proxies')
export const proxyReload = () => apiJson('/api/admin/spine/proxies/reload', { method: 'POST' })
export const proxyImportFile = () => apiJson('/api/admin/spine/proxies/import-file', { method: 'POST' })
export const proxyClear = (hash: string) => apiJson(`/api/admin/spine/proxies/${encodeURIComponent(hash)}/clear`, { method: 'POST' })
export const proxyCheck = (payload: Dict<any> = {}) => apiJson('/api/admin/spine/proxies/check', { method: 'POST', ...jsonBody(payload) })
export const proxyAntiBotDiagnostics = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/proxies/anti-bot${qs(p)}`)
export const proxyAntiBotCheck = (payload: Dict<any> = {}) => apiJson('/api/admin/spine/proxies/anti-bot/check', { method: 'POST', ...jsonBody(payload) })
export const proxyAntiBotApplyRules = (payload: Dict<any> = {}) => apiJson('/api/admin/spine/proxies/anti-bot/apply-rules', { method: 'POST', ...jsonBody(payload) })
export const proxyEndpointCreate = (payload: Dict<any>) => apiJson('/api/admin/spine/proxies/endpoints', { method: 'POST', ...jsonBody(payload) })
export const proxyEndpointBulkUpsert = (payload: Dict<any>) => apiJson('/api/admin/spine/proxies/endpoints/bulk', { method: 'POST', ...jsonBody(payload) })
export const proxyEndpointUpdate = (id: number, payload: Dict<any>) => apiJson(`/api/admin/spine/proxies/endpoints/${id}`, { method: 'PATCH', ...jsonBody(payload) })
export const proxyEndpointCheck = (id: number, payload: Dict<any> = {}) => apiJson(`/api/admin/spine/proxies/endpoints/${id}/check`, { method: 'POST', ...jsonBody(payload) })
export const proxyEndpointCheckBatch = (payload: Dict<any> = {}) => apiJson('/api/admin/spine/proxies/endpoints/check-batch', { method: 'POST', ...jsonBody(payload) })
export const proxyNetworkDiagnostics = (payload: Dict<any> = {}) => apiJson('/api/admin/spine/proxies/network-diagnostics', { method: 'POST', ...jsonBody(payload) })
export const proxyMaintenance = (payload: Dict<any> = {}) => apiJson('/api/admin/spine/proxies/maintenance', { method: 'POST', ...jsonBody(payload) })
export const proxyPoolCreate = (payload: Dict<any>) => apiJson('/api/admin/spine/proxies/pools', { method: 'POST', ...jsonBody(payload) })
export const proxyPoolUpdate = (id: number, payload: Dict<any>) => apiJson(`/api/admin/spine/proxies/pools/${id}`, { method: 'PATCH', ...jsonBody(payload) })
export const proxyPoolMemberUpsert = (poolId: number, payload: Dict<any>) => apiJson(`/api/admin/spine/proxies/pools/${poolId}/members`, { method: 'POST', ...jsonBody(payload) })
export const proxyRuleCreate = (payload: Dict<any>) => apiJson('/api/admin/spine/proxies/rules', { method: 'POST', ...jsonBody(payload) })
export const proxyRuleUpdate = (id: number, payload: Dict<any>) => apiJson(`/api/admin/spine/proxies/rules/${id}`, { method: 'PATCH', ...jsonBody(payload) })
