import { apiJson, jsonBody, qs, type Dict } from './client'

export const inventory = () => apiJson('/api/admin/spine/inventory')
export const tenants = () => apiJson('/api/admin/spine/tenants')
export const config = () => apiJson('/api/admin/spine/config')
export const audit = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/audit${qs(p)}`)
export const dataQuality = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/data-quality${qs(p)}`)
export const dataQualityProducts = (site: string, p: Dict<any> = {}) => apiJson(`/api/admin/spine/data-quality/${encodeURIComponent(site)}/products${qs(p)}`)
export const siteCrawlerConfig = (site: string) => apiJson(`/api/admin/spine/sites/${encodeURIComponent(site)}/crawler-config`)
export const siteCrawlerConfigUpdate = (site: string, payload: Dict<any>) => apiJson(`/api/admin/spine/sites/${encodeURIComponent(site)}/crawler-config`, { method: 'PATCH', ...jsonBody(payload) })
export const siteCrawlerConfigTestPriceSource = (site: string, payload: Dict<any>) => apiJson(`/api/admin/spine/sites/${encodeURIComponent(site)}/crawler-config/test-price-source`, { method: 'POST', ...jsonBody(payload) })
export const crawlEnqueue = (payload: Dict<any>) => apiJson('/api/admin/spine/crawl/enqueue', { method: 'POST', ...jsonBody(payload) })
export const promotionsRebuild = (payload: Dict<any>) => apiJson('/api/admin/spine/promotions/rebuild', { method: 'POST', ...jsonBody(payload) })
export const analyticsRecompute = (payload: Dict<any>) => apiJson('/api/admin/spine/analytics/recompute', { method: 'POST', ...jsonBody(payload) })
export const thirdPartyMetricsImport = (payload: Dict<any>) => apiJson('/api/admin/spine/third-party-metrics/import', { method: 'POST', ...jsonBody(payload) })
export const thirdPartyMetricsTemplate = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/third-party-metrics/template${qs(p)}`)
export const thirdPartyMetricsValidate = (payload: Dict<any>) => apiJson('/api/admin/spine/third-party-metrics/validate', { method: 'POST', ...jsonBody(payload) })
export const proxies = () => apiJson('/api/admin/spine/proxies')
export const proxyReload = () => apiJson('/api/admin/spine/proxies/reload', { method: 'POST' })
export const proxyImportFile = () => apiJson('/api/admin/spine/proxies/import-file', { method: 'POST' })
export const proxyClear = (hash: string) => apiJson(`/api/admin/spine/proxies/${encodeURIComponent(hash)}/clear`, { method: 'POST' })
export const proxyCheck = (payload: Dict<any> = {}) => apiJson('/api/admin/spine/proxies/check', { method: 'POST', ...jsonBody(payload) })
export const proxyAntiBotDiagnostics = (p: Dict<any> = {}) => apiJson(`/api/admin/spine/proxies/anti-bot${qs(p)}`)
export const proxyAntiBotCheck = (payload: Dict<any> = {}) => apiJson('/api/admin/spine/proxies/anti-bot/check', { method: 'POST', ...jsonBody(payload) })
export const proxyAntiBotApplyRules = (payload: Dict<any> = {}) => apiJson('/api/admin/spine/proxies/anti-bot/apply-rules', { method: 'POST', ...jsonBody(payload) })
export const proxyEndpointCreate = (payload: Dict<any>) => apiJson('/api/admin/spine/proxies/endpoints', { method: 'POST', ...jsonBody(payload) })
export const proxyEndpointUpdate = (id: number, payload: Dict<any>) => apiJson(`/api/admin/spine/proxies/endpoints/${id}`, { method: 'PATCH', ...jsonBody(payload) })
export const proxyPoolCreate = (payload: Dict<any>) => apiJson('/api/admin/spine/proxies/pools', { method: 'POST', ...jsonBody(payload) })
export const proxyPoolUpdate = (id: number, payload: Dict<any>) => apiJson(`/api/admin/spine/proxies/pools/${id}`, { method: 'PATCH', ...jsonBody(payload) })
export const proxyPoolMemberUpsert = (poolId: number, payload: Dict<any>) => apiJson(`/api/admin/spine/proxies/pools/${poolId}/members`, { method: 'POST', ...jsonBody(payload) })
export const proxyRuleCreate = (payload: Dict<any>) => apiJson('/api/admin/spine/proxies/rules', { method: 'POST', ...jsonBody(payload) })
export const proxyRuleUpdate = (id: number, payload: Dict<any>) => apiJson(`/api/admin/spine/proxies/rules/${id}`, { method: 'PATCH', ...jsonBody(payload) })
